CREATE TABLE table_one (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  column_one VARCHAR(30) NOT NULL,
  column_tow VARCHAR(30) NOT NULL,
  column_three BOOLEAN NOT NULL
);
CREATE TABLE table_two (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  column_one VARCHAR(30) NOT NULL,
  column_tow VARCHAR(30) NOT NULL,
  column_three BOOLEAN NOT NULL
);